server:
  port: 3000
spring:
  application:
    name: user-service
  data:
    mongo: mongodb://localhost:27017/users
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
